README.md
README.md를 수정했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-270)
=> [DLG-270] README.md 를 수정한다.

dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeToken.java, dailyge-api/src/main/java/project/dailyge/app/common/utils/CookieUtils.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponCreateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/user/external/oauth/GoogleOAuthManager.java, dailyge-api/src/main/java/project/dailyge/app/core/user/external/response/GoogleAuthorizationResponse.java, dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/LoginApi.java, dailyge-api/src/test/java/project/dailyge/app/test/common/CookieUtilsUnitTest.java, dailyge-api/src/test/java/project/dailyge/app/test/common/DailygeTokenUnitTest.java, dailyge-api/src/test/java/project/dailyge/app/test/coupon/unittest/CouponCreateApiUnitTest.java, dailyge-api/src/test/java/project/dailyge/app/test/user/unittest/GoogleOAuthManagerUnitTest.java
Youl 클라이언트 작업할 때, 쿠키 로직을 수정하면서 작업하는게 보여서, 편하게 작업 하시라고 **`환경 변수에 따라 로직을 분기처리`** 했습니다.
<br/><br/><br/><br/>
앞으로는 환경 변수란에 local만 입력하시면 코드 수정 안 하셔도 될겁니다. 수고하세요. 👋
> 사용자도 별로 없고, 부하 테스트할 때 이게 성능에 크리티컬 할 것 같진 않네요.
<br/><br/><br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-277)
=> [DLG-277] 클라이언트 작업 생산성을 위해 환경 변수에 따라 로직을 분기처리한다.

.gitignore, dailyge-api/build.gradle, dailyge-api/src/main/java/project/dailyge/app/CommonApi.java, dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java, dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java, dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/LoggingConfig.java, dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/WebConfiguration.java, dailyge-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java, dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java, dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java, dailyge-api/src/main/java/project/dailyge/app/common/log/MdcTaskDecorator.java, dailyge-api/src/main/java/project/dailyge/app/common/log/package-info.java, dailyge-api/src/main/java/project/dailyge/app/common/utils/IpUtils.java, dailyge-api/src/test/java/project/dailyge/app/test/common/DailygeUserUnitTest.java, dailyge-api/src/test/java/project/dailyge/app/test/common/MdcTaskDecoratorUnitTest.java, support/build.gradle, support/src/main/java/project/dailyge/app/constant/LogConstant.java, support/src/main/java/project/dailyge/app/utils/LogUtils.java, support/src/test/java/project/dailyge/support/test/log/LogUtilsUnitTest.java
로그를 CloudWatch로 전송하는 작업을 했습니다. 
<br/><br/>
로그에 순서를 추가해 조금 더 알아보기 편하도록 코드를 수정했습니다. 또한 기존에는 랜덤 UUID를 사용했는데, 로그에 추가작업을 하기 위해 Timebased UUID로 변경했습니다.
```shell
{"order":"1", "layer":"ENTRANCE", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.625", "duration":"0ms", "context":{"args":null, "result":null}}
{"order":"2", "layer":"APPLICATION", "path":"/api/health-check", "method":"GET", "traceId":"8866b9cd-70c0-11ef-ac4a-29b05d3793cc", "ip":"0:0:0:0:0:0:0:1", "visitor":{"userId":null,"role":"GUEST"}, "time":"2024-09-12T13:36:09.649", "duration":"0ms", "context":{"args":"[eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjY0NTAzMDMsInN1YiI6ImJmMmUyZDY0ZmRhNWQ4N …
```
=> [DLG-282] CloudWatch로 로그를 전송한다.

dailyge-api/src/main/java/project/dailyge/app/core/common/web/Cookies.java, dailyge-api/src/main/java/project/dailyge/app/core/common/web/LoginInterceptor.java, dailyge-api/src/test/java/project/dailyge/app/test/common/CookiesUnitTest.java, dailyge-api/src/test/java/project/dailyge/app/test/common/LoginInterceptorUnitTest.java
로그인 요청 시 Logged-In 쿠키도 체크하도록 하였습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-287)
=> [DLG-287] User 로그인 시 Logged-In 쿠키를 체크한다.

dailyge-api/src/main/java/project/dailyge/app/core/user/application/command/UserUpdateCommand.java, dailyge-api/src/main/java/project/dailyge/app/core/user/event/UserEventListener.java, dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java, dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserUpdateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/request/UserUpdateRequest.java, dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/UserUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserUpdateSnippet.java
사용자 cache 정보 수정 API 개발하였습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-288)
=> [DLG-288] User Cache 정보 수정 API를 개발한다.

dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserSnippet.java
체크 스타일 수정 사항 빈 공백을 삭제하였습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-307)
=> [DLG-307] 체크 스타일 수정사항을 반영한다.

dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
Cache 검색 시 잘못된 분기문을 수정하였습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-311)
=> [DLG-311] Cache 검색 시 잘못된 분기문을 수정한다.

dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
상세 내용은 [v1.0.5](https://github.com/dailyge/dailyge-server/releases/tag/v1.0.5) 항목을 참조해주세요.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-312)
=> [DLG-312] v1.0.5을 상용 서버에 배포한다.

dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java, dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java, storage/rdb/src/main/java/project/dailyge/entity/event/EventJpaEntity.java
EventJpaEntity의 불필요한 Import로 인해 CheckStyle, PMD 규칙에 걸렸고, 배포가 실패했습니다. 
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-317)
=> [DLG-317] 불필요한 Import를 제거한다.

dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/configuration/BlockingQueueConfig.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventBulks.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponCreateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponSchedulerApi.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/request/ScheduleRateRequest.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/response/CouponParticipationResponse.java, dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/validator/CouponClientValidator.java, dailyge-api/src/main/java/project/dailyge/app/core/event/presentation/EventCreateApi.java, dailyge-api/src/test/java/project/dailyge/app/test/coupon/documentationtest/snippet/CouponCreateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponBulkSchedulerTest.java, dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventValidationIntegrationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/event/unittest/EventValidatorUnitTest.java
pmd rule에 맞게 수정했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-318)
=> [DLG-318] 테스트 클래스를 default로 변경한다.

dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java, dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java, dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventValidationIntegrationTest.java
부하테스트 끝나서 로그 비활성화 PR revert 합니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-332)
=> [REVERT-188] 부하테스트를 위해 로그를 비활성화한다.

dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/AnniversaryWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/usecase/AnniversaryWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/AnniversaryCreateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/AnniversaryDeleteApi.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/AnniversaryDeleteDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversaryDeleteSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversarySnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/integrationtest/AnniversaryDeleteIntegrationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/integrationtest/AnniversarySaveIntegrationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/common/DailygeUserUnitTest.java, storage/rdb/src/main/java/project/dailyge/entity/anniversary/AnniversaryJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/anniversary/AnniversaryJpaEntityUnitTest.java
기념일을 삭제하는 API를 개발했습니다. 삭제 시, 물리적인 삭제를 하지 않고, Soft Delete 처리했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-346)
=> [DLG-346] 기념일 삭제 API를 개발한다.

dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/AnniversaryWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/command/AnniversaryUpdateCommand.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/usecase/AnniversaryWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/facade/AnniversaryFacade.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/AnniversaryUpdateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/request/AnniversaryUpdateRequest.java, dailyge-api/src/test/java/project/dailyge/app/common/snippet/CommonSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/AnniversaryUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversaryCreateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversaryDeleteSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversarySnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversaryUpdateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/integrationtest/AnniversaryUpdateIntegrationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/monthlygoal/documentationtest/snippet/MonthlyGoalCreateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/monthlygoal/documentationtest/snippet/MonthlyGoalDeleteSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/monthlygoal/documentationtest/snippet/MonthlyGoalSearchSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/monthlygoal/documentationtest/snippet/MonthlyGoalUpdateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskCreateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskDeleteSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskReadSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskStatisticSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskUpdateSnippet.java, storage/rdb/src/main/java/project/dailyge/entity/anniversary/AnniversaryJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/anniversary/AnniversaryJpaEntityUnitTest.java
기념일 수정 API를 개발했습니다. 
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-347)
=> [DLG-347] 기념일 수정 API를 개발한다.

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/CommonUtils.kt, dailyge-api/build.gradle, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/AnniversaryReadService.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/application/usecase/AnniversaryReadUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/persistence/AnniversaryEntityReadDao.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/AnniversaryReadApi.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/response/AnniversaryResponse.java, dailyge-api/src/main/java/project/dailyge/app/core/anniversary/presentation/validator/AnniversaryClientValidator.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/AnniversaryReadDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversaryReadSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/documentationtest/snippet/AnniversarySnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/integrationtest/AnniversaryReadIntegrationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/anniversary/unittest/AnniversaryClientValidatorUnitTest.java, storage/rdb/src/main/java/project/dailyge/entity/anniversary/AnniversaryEntityReadRepository.java, storage/rdb/src/main/java/project/dailyge/entity/anniversary/AnniversaryJpaEntity.java
기념일 조회 API를 개발했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-348)
=> [DLG-348] 기념일 조회 API를 개발한다.

dailyge-api/src/main/java/project/dailyge/app/core/retrospect/application/RetrospectWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/application/command/RetrospectUpdateCommand.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/application/usecase/RetrospectReadUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/application/usecase/RetrospectWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/application/usecase/RetrospectWriteUserCase.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityReadDao.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/persistence/RetrospectEntityWriteDao.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/RetrospectUpdateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/retrospect/presentation/request/RetrospectUpdateRequest.java, dailyge-api/src/test/java/project/dailyge/app/test/retrospect/documentationtest/RetrospectUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/retrospect/documentationtest/snippet/RetrospectSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/retrospect/documentationtest/snippet/RetrospectUpdateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/retrospect/integrationtest/RetrospectUpdateIntegrationTest.java, storage/rdb/src/main/java/project/dailyge/entity/retrospect/RetrospectJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/retrospect/RetrospectUnitTest.java
회고 수정 API를 개발하였습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-351)
=> [DLG-351] 회고 수정 API를 개발한다.

dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/WeeklyGoalWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/command/WeeklyGoalCreateCommand.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalWriteDao.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalCreateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/request/WeeklyGoalCreateRequest.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/response/WeeklyGoalCreateResponse.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/WeeklyGoalCreateIntegrationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalCreateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/snippet/WeeklyGoalCreateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/snippet/WeeklyGoalSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/integrationtest/WeeklyGoalCreateIntegrationTest.java, storage/rdb/src/main/java/project/dailyge/entity/weeklygoal/WeeklyGoalEntityWriteRepository.java
주간 목표 작성 API를 개발했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-352)
=> [DLG-352] 주간 목표 작성 API를 개발한다.

dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/WeeklyGoalWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/command/WeeklyGoalUpdateCommand.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/exception/WeeklyGoalCodeAndMessage.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/exception/WeeklyGoalTypeException.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/persistence/WeeklyGoalReadDao.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalUpdateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/request/WeeklyGoalStatusUpdateRequest.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/request/WeeklyGoalUpdateRequest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalCreateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalDoneUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/snippet/WeeklyGoalSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/snippet/WeeklyGoalUpdateSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/integrationtest/WeeklyGoalUpdateIntegrationTest.java, storage/rdb/src/main/java/project/dailyge/entity/weeklygoal/WeeklyGoalEntityReadRepository.java, storage/rdb/src/main/java/project/dailyge/entity/weeklygoal/WeeklyGoalJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/weeklygoal/WeeklyGoalJpaEntityUnitTest.java
주간 목표 수정 API를 개발했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-355)
=> [DLG-355] 주간 목표 수정 API를 개발한다.

dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/WeeklyGoalWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/application/usecase/WeeklyGoalWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalDeleteApi.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalDeleteDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/snippet/WeeklyGoalDeleteSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/integrationtest/WeeklyGoalDeleteIntegrationTest.java
주간 목표 삭제 API를 개발했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-358)
=> [DLG-358] 주간 목표 삭제 API를 개발한다.

dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalCreateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalReadApi.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/WeeklyGoalUpdateApi.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/request/WeeklyGoalCreateRequest.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/request/WeeklyGoalStatusUpdateRequest.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/request/WeeklyGoalUpdateRequest.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/response/WeeklyGoalCreateResponse.java, dailyge-api/src/main/java/project/dailyge/app/core/weeklygoal/presentation/response/WeeklyGoalResponse.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalCreateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalDoneUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalReadDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/WeeklyGoalUpdateDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/weeklygoal/documentationtest/snippet/WeeklyGoalSnippet.java, storage/rdb/src/main/java/project/dailyge/entity/anniversary/AnniversaryJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/country/Country.java, storage/rdb/src/main/java/project/dailyge/entity/coupon/FreeCouponJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/emoji/EmojiJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/event/EventImageJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/holiday/HolidayJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/monthlygoal/MonthlyGoalJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/notice/NoticeJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/retrospect/RetrospectJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/task/MonthlyTaskJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/user/UserJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/monthlygoal/MonthlyGoalJpaEntityUnitTest.java, storage/rdb/src/test/java/project/dailyge/entity/test/notice/NoticeJpaEntityUnitTest.java, storage/rdb/src/test/java/project/dailyge/entity/test/retrospect/RetrospectUnitTest.java, storage/rdb/src/test/java/project/dailyge/entity/test/task/TaskJpaEntityUnitTest.java
주간 목표 패키지 구조 수정 및 엔티티 제어자를 protected로 수정했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-364)
=> [DLG-364] 주간 목표 패키지 구조를 수정한다.

storage/rdb/src/main/java/project/dailyge/entity/user/UserJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/user/UserJpaEntityUnitTest.java
회원가입 시, 닉네임, 이메일 정규식을 수정한다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-384)
=> [DLG-384] 회원가입 시, 닉네임, 이메일 정규식을 수정한다.

dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/CorsFilter.java, dailyge-api/src/main/java/project/dailyge/app/core/note/application/NoteReadService.java, dailyge-api/src/main/java/project/dailyge/app/core/task/application/TaskRecurrenceWriteService.java, dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskRecurrenceWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskValidator.java, dailyge-api/src/main/java/project/dailyge/app/core/task/application/usecase/TaskWriteUseCase.java, dailyge-api/src/main/java/project/dailyge/app/core/task/persistence/TaskRecurrenceReadDao.java, dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskRecurrenceDeleteApi.java, dailyge-api/src/test/java/project/dailyge/app/test/common/CorsFilterUnitTest.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/TaskRecurrenceDeleteDocumentationTest.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskRecurrenceDeleteSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/documentationtest/snippet/TaskSnippet.java, dailyge-api/src/test/java/project/dailyge/app/test/task/integrationtest/TaskRecurrenceDeleteIntegrationTest.java, storage/rdb/src/main/java/project/dailyge/entity/task/TaskJpaEntity.java, storage/rdb/src/main/java/project/dailyge/entity/task/TaskRecurrenceEntityReadRepository.java, storage/rdb/src/main/java/project/dailyge/entity/task/TaskRecurrenceJpaEntity.java, storage/rdb/src/test/java/project/dailyge/entity/test/task/TaskRecurrenceJpaEntityUnitTest.java
반복 일정 삭제 API 개발했습니다.
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-392)
=> [DLG-392] 반복 일정 삭제 API 개발

README.md
회고, 통계 등 추가되었던 기능들에 대한 사진 첨부 및 Discussions에 대한 Content 내용을 추가하였습니다.
<br/><br/>
<br/><br/>
- [Ticket](https://jungjunwoojun.atlassian.net/jira/software/projects/DLG/boards/4?selectedIssue=DLG-394)
=> [DLG-394] README.md를 수정한다.
